### ISSUE TITLE
stopped working: gulp depreciated

### ISSUE THREAD

**Issue by coolajami** [uPaymeiFixit/forecast-widget#2]
HI
the widget stopped working, gulp command is now depreciated. I tried to go around it but it does seem to require quite a lot of work, that I think it may be making the widget unusable for most of the users.

**Comment by uPaymeiFixit** [comment]
Thanks for letting me know. I'll see what I can do when I have some free-time. But fair warning, it's been a while since I've really worked on this project, so it may not be quick.

**Comment by uPaymeiFixit** [comment]
While the widget does use an older version of Gulp, it should still work. You may have run into a version mismatch with your global version of Gulp. Try running the local version with `node ./node_modules/gulp/bin/gulp.js`

**Comment by coolajami** [comment]
Hi, thanks for looking into this, you tip worked for me very well! Great widget, it does seem to put a lot of effort in its design :)
Gulp is only partially working, it does not completely compile, I think it stuck when try to start the build command. The good thing is that it seems that the only thing that is affected is the font and the widget appears in Times New Roman (Doesn't pull the Roboto font). I tried to fix this by doing a bit of tweaking of the index.js (after compile) and even the style.scss (before compile). Couldn't fix it, but still happy with current font :)

A kind note,  in the gulpfile.js in line 93, there is the folder path for the widget, it will be easier if there was a note to change to the users' local folder, otherwise, the compiler may be stuck, if there is no user permission to create folders in the root directory. Finally in the compile-index.js line 39 if you tweak the buffer() to buffer.from(to) allows the gulp to run a bit more uneventfully.
