### ISSUE TITLE
Dark Sky will be shut down

### ISSUE THREAD

**Issue by corporate-gadfly** [uPaymeiFixit/forecast-widget#4]
Since Dark Sky will be shutting down (soon?), do you have any plans to switch to something like [OpenWeather](https://openweathermap.org/api/one-call-api)?

**Comment by uPaymeiFixit** [comment]
I would be open to a PR, but at the moment I'm not maintaining any Übersicht widgets as Übersicht uses far too much resource and I haven't had time to diagnose why.
